# Database Configuration
database:
  driver: postgres  # sqlite or postgres
  # SQLite configuration
  # path: ./data/emailtoapi.db
  # PostgreSQL configuration (when driver is postgres)
  host: localhost
  port: 5432
  user: postgres
  password: ""
  name: emailtoapi
  sslmode: disable

# Admin Server Configuration
adminserver:
  host: 0.0.0.0
  port: 8080

# Mail Server Configuration
mailserver:
  domain: example.com  # Domain for generated email addresses
  receivemethod: smtp  # smtp or webhook
  maxemailsize: 10485760  # 10MB in bytes
  maxretries: 10
  retrydelay: 5
  smtphost: 0.0.0.0
  smtpport: 25

# Mailgun Configuration (optional)
mailgun:
  apikey: ""
  domain: ""
  fromaddress: ""
  site_domain: example.com # Domain for registration link if mailgun is used