name: goreleaser

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
      -
        name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc \
            musl-dev \
            musl-tools \
            sqlite3 \
            libsqlite3-dev \
            libc6-dev
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CC_linux_arm64: aarch64-linux-gnu-gcc
          CXX_linux_arm64: aarch64-linux-gnu-g++
          AS_linux_arm64: aarch64-linux-gnu-as
          PKG_CONFIG_PATH_linux_arm64: /usr/lib/aarch64-linux-gnu/pkgconfig
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}